### ISSUE TITLE
what is the point of reverse engeniring open source application??

### ISSUE THREAD

**Issue by Marcinoo97** [sidd-kishan/WorCP#4]
this repo surves no purpose and its just a waste of github's platform.

**Comment by plooshi** [comment]
agreed, its not even the latest :/

**Comment by sidd-kishan** [comment]
Dear @Marcinoo97 @plooshi , If we focus on creating wifi driver it will yeild community more  benifit rather than wasting our time posting in github random questions.

**Comment by Marcinoo97** [comment]
> Dear @Marcinoo97 @plooshi , If we focus on creating wifi driver it will yeild community more benifit rather than wasting our time posting in github random questions.

we already have wifi drivers.  and asking random questions on github was your favourite thing so how was it a waste of time?     Also delete this repo as my it appears above my repo when searched on bing.

**Comment by sidd-kishan** [comment]
@Marcinoo97 I will not delete this repo.
